### ISSUE TITLE
Expires header not sufficient to bypass browser caching

### ISSUE THREAD

**Issue by ebudan** [epicagency/caddy-expires#1]
This is noticed on Chrome (Version 54.0.2840.71 (64-bit)) and Firefox (49.0.2) on OS X:  
The Expires header itself is not enough to persuade the browser to reload a modified page.
In Safari, seems to work as expected.

(Edit: removed comment regarding Last-Modified - was not correct. Added browser info.)

**Comment by ebudan** [comment]
Adding the following in ServeHTTP() would seem to resolve caching in the mentioned browsers:
  
    ...
    w.Header().Set("Cache-Control", "public, max-age="+strconv.Itoa(int(rule.Duration.Seconds()))) 
    ...

**Comment by hlidotbe** [comment]
ok. That I can do.

Setting Last-Modified should be done by Caddy itself as it would make much more sense.

**Comment by hlidotbe** [comment]
Done (finally)
