### ISSUE TITLE
Plugin is incompatible with cloudflare provider

### ISSUE THREAD

**Issue by bendem** [epicagency/caddy-expires#9]
I tried updating caddy recently, but I had to disable this plugin because it will not work when included together with `tls.dns.cloudflare`. It works fine when it is used alone.

You can reproduce the problem from your command line using:

```
curl "https://caddyserver.com/download/linux/amd64?license=personal&telemetry=off&plugins=http.expires,tls.dns.cloudflare"
provisioning build environment: go mod init: exit status 1
```

**Comment by hlidotbe** [comment]
I just did that and it builds correctly both locally and through caddy build server.
I was probably an issue either with the cloudflare plugin or the build server.

**Comment by bendem** [comment]
Guess so, thanks for getting back to me.
